name: Main Workflow

on:
  schedule:
    - cron: "0 */2 * * *"
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.token || github.token }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        if: ${{ github.token || false }}
        run: npm i -g yarn

      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - run: yarn lint
